### ISSUE TITLE
Contributor Credit

### ISSUE THREAD

**Issue by 4bitfocus** [4bitfocus/SlightlyImprovedExperienceBar#5]
I think this addon needs a way to recognize contributors (@Shadowfen and @Arthmoor). I feel my role now is mostly an organizer (and possibly "original author"). I'm too sucked into WoW and HotS to have time for ESO, but I don't want this addon to splinter and result in a bunch of copies. I'd love to hear any thoughts on how we can give contributors just credit.

**Comment by Arthmoor** [comment]
I'm not sure how it would be done (or if it even can) but I'd be fine with a listing as a contributor in the UI or something. At the very least the readme should probably have some mention of contributors.

**Comment by Shadowfen** [comment]
Looked at some of the other mods I have with multiple people, and most seem
to acknowledge contributors in the Mod Description on Minion. The only way
to do something inside the mod itself would probably be in some sort of
comment header section in the main lua file. Possibly could be done as ';'
comment lines in the txt file as well?

Shadowfen

**Comment by 4bitfocus** [comment]
I updated the ReadMe.md file to include a contributor section. Feel free to edit the link to whatever you would like/prefer. Thanks for all your help.
